// Test: Ignorar error expl√≠citamente con _
// Expected: Compilar sin warnings, puede panic

getUser(id: number): Result<User, string> {
    if id == 0 {
        return Err("Invalid ID")
    }
    return Ok(User("Test User", id))
}

User {
    name: string
    id: number
}

main() {
    // Ignorar error con _
    let user, _ = async getUser(1)
    print($"User: {user.name}")
}
